config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'

  get 'sign_in', to: 'users#signin'
  post 'sign_in', to: 'users#signedin'

  delete 'logout', to: 'users#destroy'

  get '/projects/no-group', to: 'projects#no_group'

  resources :users, only: %i[create show edit update]

  resources :projects, only: %i[index show new create]

  resources :groups, only: %i[index show new create]

  root 'main#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :projects

  validates :name, presence: true, uniqueness: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true

  validates :name, presence: true, length: { in: 4..18 }
  validates :description, presence: true, length: { in: 10..160 }
  validates :amount, presence: true, numericality: true
  validates :user_id, presence: true

  scope :ug_incl, -> { includes(:user, :group) }
  scope :desc, -> { order('created_at DESC') }
end

app/models/user.rb
class User < ApplicationRecord
  before_create { self.icon = Faker::Avatar.image }

  has_many :groups
  has_many :projects

  validates :name, presence: true, uniqueness: true
  validates :name, length: { minimum: 4, maximum: 18 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :already_in, :signed_in_user, :current_user, :logged_in?

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def signed_in_user
    return if logged_in?

    flash[:alert] = 'Please login or signup to have access'
    redirect_to root_path
  end

  def already_in
    redirect_to current_user if logged_in?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include GroupsHelper
  before_action :signed_in_user, only: %i[new create index show]

  def new
    @icons = icons
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      flash[:notice] = "'#{@group.name}' group created successfully!"
      redirect_to @group
    else
      @icons = icons
      render 'new'
    end
  end

  def index
    @groups = Group.all.order('name')
  end

  def show
    @group = Group.find_by(id: params[:id])
    @projects = Project.ug_incl.where(group_id: @group.id).desc
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :user)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :signed_in_user, only: %i[new create show index]

  def new
    @project = Project.new
    @groups = Group.all.collect { |group| [group.name, group.id] }
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      flash[:notice] = "#{@project.name} project successfully created"
      redirect_to @project
    else
      render 'new'
    end
  end

  def show
    @project = Project.find_by(id: params[:id])
  end

  def index
    @projects = Project.ug_incl.where(user_id: current_user.id).desc
  end

  def no_group
    @projects = Project.ug_incl.where({ group_id: nil, user_id: current_user.id }).desc
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :amount, :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "#{@user.name}, your account was created successfully."
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @user.name == user_params[:name]
      flash[:alert] = 'Try again, name already exists'
      redirect_to edit_user_path
    elsif @user.update(user_params)
      redirect_to @user, notice: 'Your display name was successfully updated.'
    else
      render :edit
    end
  end

  # session  methods
  def signin; end

  def signedin
    user = User.find_by(name: params[:name])

    if user.present?
      session[:user_id] = user.id
      redirect_to user, notice: "#{user.name} Logged in successfully"
    else
      flash[:alert] = 'Invalid User'
      render 'signin'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'logged out'
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def set_user
    @user = User.find_by(id: session[:user_id])
  end
end

app/helpers/application_helper.rb
# rubocop:disable Layout/BlockAlignment
# rubocop:disable Layout/LineLength
# rubocop:disable Style/RedundantInterpolation

module ApplicationHelper
  def show_alive
    if flash[:alert]
      render(partial: 'shared/alert')
    elsif flash[:notice]
      render(partial: 'shared/notice')
    elsif flash[:warning]
      render(partial: 'shared/warning')
    end
  end

  def show_errors(inst)
    content = ''
    if inst.errors.any?
      inst.errors.full_messages.each do |m|
        content << "<div class='bg-red-100 text-red-900 px-5 py-3 rounded-md mp:mx-3 text-center'>
                      <div>#{m}</div>
                    </div>"
      end
    end
    content.html_safe
  end

  def navbar(name)
    render(partial: 'layouts/nav') unless %w[Home Profile].any? name
  end

  def navlink(*)
    content = ''
    content << if logged_in?
                 "<a href='/users/ #{current_user.id}'>"
               else
                 "<a href='/'>"
               end
    content.html_safe
  end

  def show_project(project)
    content = ''
    content << if project.group
                 "<img src=' #{project.group.icon} ' alt='' class='h-20 w-20 my-auto'>"
               else
                 "<div class='my-auto h-20 w-20 border rounded-md border-gray-300'>
                  <small class='block text-center mt-5 font-bold'>no group</small>
                  </div>"
               end
    content.html_safe
  end

  def new_group
    content = ''
    content << "#{link_to new_group_path do
       'NEW GROUP'
     end}"
    content.html_safe
  end

  def new_project
    content = ''
    content << "#{link_to new_project_path do
       'NEW PROJECT'
     end}"
    content.html_safe
  end

  def show_proj_group(project)
    content = ''
    content << if project.group
                 "<img src='#{project.group.icon}' alt='' class='h-20 w-20 my-auto'>"
               else
                 "<div class='my-auto ml-2 h-28 w-28 border rounded-md border-gray-300'>
                   <small class='block text-center mt-5 font-bold'>no group</small>
                   </div>"
               end
    content.html_safe
  end

  def show_proj_name(project)
    content = ''
    if controller_name == 'groups' && action_name == 'show'
      content << "<p class='font-bold mr-3 text-md'>
                  <small class='font-medium mr-1'>
                  created by </small>  #{project.user.name} </p>"
    end
    content.html_safe
  end

  def show_icons(ico)
    content = ''
    1.upto(20) do |i|
      content << "<li class='p-4 m-1'>
                  #{ico.radio_button :icon, @icons[i]['link'], class: 'focus:ring-secondary h-4 w-4 text-secondary border-gray-300'}"
      content << "#{ico.label :icon, value: @icons[i]['link'], class: 'w-2 h-2 py-4' do
                    image_tag(@icons[i]['link'], class: 'w-14 h-14')
                  end}"
      content << '</li>'
    end
    content.html_safe
  end
end
# rubocop:enable Style/RedundantInterpolation
# rubocop:enable Layout/LineLength
# rubocop:enable Layout/BlockAlignment

app/helpers/groups_helper.rb
module GroupsHelper
  def icons
    html_data = RestClient.get('https://www.flaticon.com/packs/web-design-122?word=code')
    nok_obj = Nokogiri::HTML(html_data)
    tags = nok_obj.xpath('//html/body/section/div/div/section/ul/li')
    i_hash = {}
    tags.each_with_index do |li, i|
      i_hash[i] = {
        'name' => li['data-name'],
        'link' => li['data-icon_src'],
        'auth' => li['data-author_name']
      }
    end
    i_hash
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def logged_in_user
    return if logged_in?

    flash[:alert] = 'Please login or signup to have access'
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_group.html.erb
 <a href="<%= group_url(group.id) %>" class="text-decoration-none w-full">
  <div class="group-partial-container">
    <img src="<%= group.icon %>" alt="" class="h-20 w-20 my-auto">
    <p class="text-decoration-none h4 m-0 align-self-center px-1 overflow-hidden font-bold text-lg mp:text-sm">
      <%= group.name %>
    </p>
    <p class="m-0 pr-2 align-self-center text-center">
      <small class=""><%= group.created_at.strftime('%d %b %Y') %></small>
    </p>
  </div>
</a>

app/views/groups/index.html.erb
<% provide(:title, 'Groups') %>

<div class="group-container">
  <div class="w-full flex justify-between items-center px-5 py-5">
    <div class="w-full">
      <%= render @groups %>
    </div>
    
  </div>

  <div class="w-full text-center py-4 text-white bg-secondary px-6">
    <div class="py-4 border-white border-2 rounded-lg hover:bg-secondaryDark duration-200">
      <%= new_group %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>
<div class="group-container">
<div class="w-full space-y-8">
<%= form_for @group, html: { class: "mt-5 mx-3" } do |f| %>
  <%= show_alive %>
  <%= show_errors(@group) %>
  <div>
    <%= f.text_field :name, class: "ngroup-name", placeholder: "Name" %>
  </div>
    <ul class="bg-white border border-gray-300 rounded-md">
      <p class=" text-muted w-100 text-center border-b border-gray-300 py-2">select a group</p>
        <div class="grid grid-cols-5">           
            <%= show_icons(f) %>
        </div>
    </ul>

  <div class="mt-6 flex flex-col items-center">
     <%= f.submit class: "ngroup-submit" %>
  </div>
<% end %>
</div>
</div>

app/views/groups/show.html.erb
<% provide(:title, 'Group Details') %>
<div class="group-container">
<ul class="mx-3 p-3 w-full mb-3">
  <%= show_alive %>
  <li class="flex justify-between border-b w-full items-center mb-3 pb-3">
    <h4 class="text-decoration-none h4 m-0 align-self-center px-1 overflow-hidden font-bold text-xl"><%= @group.name %></h4>
    <img src="<%= @group.icon %>" alt="" class="h-20 w-20 my-auto">
  </li>

  <li class="p-0 pt-3 w-full">
    <%= render @projects %>
  </li>

  <li class="flex justify-between mt-3 mb-3  p-2 bg-white border border-gray-300 rounded-lg mp:text-sm">
    <p class="font-medium ">TOTAL AMOUNT</p>
    <span class="font-bold"><%= number_with_precision(@projects.sum(:amount), :precision => 2) %> hrs</span>
  </li>
</ul>
  <div class="text-lg text-center w-full mt-10 pt-40">
    <%= link_to 'Go back', groups_path, class: "p-3 rounded-md text-white bg-primaryLight hover:bg-primaryDark duration-150" %>
  </div>

<div class="w-full text-center py-4 text-white bg-secondary px-6">
    <div class="py-4 border-white border-2 rounded-lg hover:bg-secondaryDark duration-200">
      <%= new_group %>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="flex items-center w-full min-h-1 bg-primaryDark">
  <nav class="navbar navbar-dark flex justify-between content-center w-full px-4">
    <div class="self-center text-xl">
      <%= navlink(logged_in?)  %>
        <button class="focus:outline-none">
          <i class="far fa-bars text-white"></i>
        </button>
      </a>
    </div>

    <div class="">
      <h4 class="top-title"><%= yield(:title).upcase %></h4>
    </div>
    <div></div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupOurProjects</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta property="og:title" content="Group our projects">
    <meta property="og:image" content="https://raw.githubusercontent.com/AshakaE/group-our-projects/develop/screenshots/meta-preview.jpg">
    <meta property="og:site_name" content="https://mighty-badlands-86456.herokuapp.com/">
    <meta property="og:description" content="This is an application built with Ruby on Rails to help team members organize projects.">
    <meta property="twitter:card" content="summary">
    <meta property="twitter:url" content="https://mighty-badlands-86456.herokuapp.com/">
    <meta property="twitter:title" content="Group our peojects">
    <meta property="twitter:description" content="This is an application built with Ruby on Rails to help team members organize projects.">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.12.0/css/all.css">
  </head>

  <body class="font-body bg-primaryLight min-h-screen">
    
    <div class="max-w-2xl flex flex-1 flex-col items-center justify-center bg-gray-50 mx-auto min-h-full">

        <%= navbar yield(:title) %>
    
        <%= yield %>

    </div>
  </body>
</html>

app/views/main/home.html.erb
 <% provide(:title, 'Home') %>
<div class="min-h-full flex items-center justify-center bg-gray-50 w-10/12">
  <div class="flex-auto my-20 space-y-8">
    <%= show_alive %>
      <h1 class="mt-6 text-center text-3xl font-extrabold text-gray-900 mb-3">Group Our Projects</h1>  
      <div class="mb-3">
            <%= link_to 'SIGN UP', sign_up_path, class: 'sign-button' %>

            <%= link_to 'LOG IN', sign_in_path, class: 'log-button-home' %>
      </div>
  </div>
</div>

app/views/projects/_project.html.erb
<a href="<%= project_url(project.id) %>" class="text-decoration-none">
  <div class="project-partial-container">
    <div class="my-auto h-20 w-20">
      <%= show_project(project) %>
    </div>
    <div class="right-content flex-grow mp:text-sm">
      <div class="flex p-3 justify-between">
        <h5 class=""><%= project.name %></h5>
        <p class="font-medium m-0">
          <%= number_with_precision(project.amount, :precision => 2) %> hrs
        </p>
      </div>

      <div class="flex justify-between">
        <p class="ml-3">
          <small class="">
            <%= project.created_at.strftime('%d %b %Y') %>
          </small>
        </p>
        <%= show_proj_name(project) %>    
      </div>
    </div>
  </div>
</a>

app/views/projects/index.html.erb
 <% provide(:title, 'Projects') %>
<div class="min-h-5 flex items-stretch justify-center flex-wrap bg-gray-50 w-full">
  <div class="w-full flex self-start justify-between shadow-md rounded-lg items-center border-b-2 border-gray-300 px-5 py-5">
    <h5 class="text-xl mp:text-lg">Total Amount</h5>
    <p class="font-bold"><%= number_with_precision(@projects.sum(:amount), :precision => 2) %> hrs</p>
  </div>

  <div class="w-full -mt-36 mx-3 self-stretch">
    <%= render @projects %>
  </div>
  
  <div class="w-full text-center self-end py-4 text-white bg-secondary px-6">
    <div class="py-4 border-white border-2 rounded-lg hover:bg-secondaryDark duration-200">
      <%= new_project %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<div class="min-h-5 flex items-center justify-center content-between flex-wrap bg-gray-50 w-full">
<div class="w-full space-y-8">
  <%= form_for @project, html: { class: "mt-5 mx-3" } do |f| %>
      <%= show_errors(@project) %>
      <div>
        <%= f.text_field :name, class: "nproject-name", placeholder: "Name" %>
      </div>
      <div>
        <%= f.text_area :description, class: "nproject-desp", placeholder: "Description" %>
      </div>
      <div class="mt-1 flex rounded-md shadow-sm">
          <span class="nproject-span">Hours</span>
          <%= f.number_field :amount, class: "nproject-amount", placeholder: "Amount", min: "0", step: "0.01" %>
      </div>
      <div class="flex flex-col items-center">
        <div class="w-full">
          <%= collection_select(:project, :group_id, Group.all, :id, :name, { :prompt => 'Group' }, class: "nproject-select" ) %>
        </div>
        <div class="mt-6">
          <%= f.submit class: "nproject-submit" %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/projects/no_group.html.erb
 <% provide(:title, 'No Group Projects') %>
<div class="min-h-5 flex items-center justify-center content-between flex-wrap bg-gray-50 w-full">
  <div class="w-full flex justify-between items-center rounded-lg shadow-md border-b-2 border-gray-300 px-5 py-5">
    <h5 class="text-xl mp:text-lg">Total Amount</h5>
    <p class="font-bold"><%= number_with_precision(@projects.sum(:amount), :precision => 2) %> hrs</p>
  </div>

  <div class="w-full -mt-48 mx-3 self-stretch">
    <%= render @projects %>
  </div>


  <div class="w-full text-center py-4 text-white bg-secondary px-6">
    <div class="py-4 border-white border-2 rounded-lg hover:bg-secondaryDark duration-200">
      <%= new_project %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, 'Details') %>
<div class="min-h-5 flex items-center justify-center content-between flex-wrap bg-gray-50 w-full">
<ul class="mx-3 p-3 w-full bg-white mt-3 border border-gray-300 rounded-md">
  <%= show_alive %>
  <li class="">
    <div class="mt-2 mb-4 flex h-32">
      <%= show_proj_group(@project) %>
      <h4 class="my-auto pl-3"><%= @project.name %></h4>
    </div>
    <p><%= @project.description %></p>
  </li>

  <li class="pt-3 flex justify-between border-t mt-2">
    <p class="">project no.<%= @project.id %></p>
    <p class=""><small><%= @project.created_at.strftime('%d %b %Y at %l:%M%P') %></small></p>
  </li>

  <li class="flex justify-between p-0 pt-3 border-t mt-2">
    <p class="m-0">AMOUNT</p>
    <span class="font-bold"><%= number_with_precision(@project.amount, :precision => 2) %> hrs</span>
  </li>
</ul>
<%= show_alive %>
<div class="w-full text-center py-4 text-white bg-secondary px-6">
    <div class="py-4 border-white border-2 rounded-lg hover:bg-secondaryDark duration-200">
      <%= new_project %>
    </div>
  </div>
</div>

app/views/shared/_alert.html.erb
<div class="text-center max-w-3xl mx-auto mb-2 mp:mx-3">
    <div class="bg-red-100 text-red-900 px-5 py-3 rounded-md" role="alert">
      <%= flash[:alert] %>
    </div>
</div>

app/views/shared/_notice.html.erb
<div class="text-center max-w-3xl mx-auto mb-2 mp:mx-3">
    <div class="bg-green-100 text-green-900 px-5 py-3 rounded-md" role="alert">
      <%= flash[:notice] %>
    </div>
</div>

app/views/shared/_warning.html.erb
<div class="text-center max-w-3xl mx-auto mb-2 mp:mx-3">
    <div class="bg-orange-100 text-orange-900 px-5 py-3 rounded-md" role="alert">
      <%= flash[:warning] %>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Profile') %>

<div class="sign-container">
<div class="w-full space-y-8">
  <div class="text-center mb-5 flex flex-col mp:mx-3">
    <h1 class="mt-6 text-center text-3xl font-extrabold text-white mb-20">Edit Name</h1>  
    <img src="<%= current_user.icon %>" alt="" class="rounded-full border h-32 w-32 mb-2 mx-auto">
    <h4 class="text-2xl mb-6"><%= current_user.name %></h4>
    <%= form_with(model: @user, local: true) do |f|%>
        <div>
          <%= f.text_field :name, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "#{current_user.name}" %>
        </div>
        <ul class="mt-8">
          <li class="mb-6 flex">
            <div class="inline-block pr-4">
                <div class="flex justify-center items-center">
                  <div class="flex justify-center items-center text-md h-10 w-10 border border-white rounded-full text-center">
                    <div class="fal fa-undo-alt"></div>
                  </div>
                </div>
            </div>
            </i>
            <div class="border-b border-white py-2 w-full flex">
              <%= link_to 'Go back', user_path %>
            </div>
          </li>
          <li class="mb-6 flex">
            <div class="inline-block pr-4">
                <div class="flex justify-center items-center">
                  <div class="flex justify-center items-center text-md h-10 w-10 border border-white rounded-full text-center">
                    <div class="fal fa-save"></div>
                  </div>
                </div>
            </div>
            </i>
            <div class="border-b border-white py-2 w-full flex">
              <%= f.submit 'Save changes', class: "no-underline cursor-pointer bg-transparent focus:outline-none" %>
            </div>
          </li>
        </ul>
        
      <%= show_errors(@user) %>
      <%= show_alive %>
  <% end %>
  </div>
</div>
</div>

app/views/users/new.html.erb
  <% provide(:title, 'Home') %>
  <div class="max-w-md w-full space-y-8">
    <%= form_with model: @user, url: sign_up_path do |f| %>
      <%= show_errors(@user) %>
      <h1 class="mt-6 text-center text-3xl font-extrabold text-gray-900 mb-40">Group Our Projects</h1> 
      <div class="mp:mx-3">
          <div>
            <%= f.label :name, class: "mt-2 text-center text-xl text-gray-600 flex justify-center mb-10" %>
            <%= f.text_field :name, class: "new-name", placeholder: 'Name' %>
          </div>
        <div class="mb-3">
          <%= f.submit 'SIGN UP', class: 'sign-new' %>
        </div>
        <div class="flex text-sm justify-center">
          <p class="pr-1">Already have an account?</p>
          <%= link_to 'Log in', sign_in_path, class: "text-primaryLight font-bold" %>
        </div>
      </div> 
    <% end %>
  </div>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>

<div class="sign-container">
<%= show_alive %>
<div class="w-full space-y-8">
  <div class="text-center mb-5 flex flex-col">
    <img src="<%= current_user.icon %>" alt="" class="rounded-full border h-32 w-32 mb-2 mx-auto">
    <%= link_to "#{current_user.name}", edit_user_path, class: "text-2xl" %>
  </div>

  <ul class="mp:mx-3">
    <li class="mb-6 flex">
      <div class="inline-block pr-4">
          <div class="flex justify-center items-center">
            <div class="font-icon">
              <div class="fal fa-project-diagram"></div>
            </div>
          </div>
      </div>
      </i>
      <div class="border-b border-white pt-2 w-full">
        <%= link_to 'All my projects', projects_path %>
      </div>
    </li>
    <li class="mb-6 flex">
      <div class="inline-block pr-4">
        <div class="flex justify-center items-center">
          <div class="font-icon">
            <div class="fal fa-tasks-alt"></div>
          </div>
        </div>
      </div>
      <div class="border-b border-white pt-2 w-full">
        <%= link_to 'All my external projects', projects_no_group_path%>
      </div>
    </li>
    <li class="mb-6 flex">
      <div class="inline-block pr-4">
        <div class="flex justify-center items-center">
          <div class="font-icon">
            <div class="fal fa-layer-group"></div>
          </div>
        </div>
      </div>
      <div class="border-b border-white pt-2 w-full">
        <%= link_to 'All groups', groups_path%>
      </div>
    </li>
    <li class="mb-6 flex ">
      <div class="inline-block pr-4">
        <div class="flex justify-center items-center">
          <div class="font-icon">
            <div class="fal fa-power-off"></div>
          </div>
        </div>
      </div>
      <div class="border-b border-white pt-2 w-full">
        <%= link_to  "Logout", logout_url, method: :delete %>
      </div>
    </li>
  </ul>
</div>
</div>

app/views/users/signin.html.erb
<% provide(:title, 'Home') %>

  <div class="max-w-md w-full space-y-8">
    <%= form_with url: sign_in_path do |f| %>
      <%= show_alive %>
      <h1 class="mt-6 text-center text-3xl font-extrabold text-gray-900 mb-40">Group Our Projects</h1> 
      <div class="mp:mx-3">
          <div>
            <%= f.label :name, class: "mt-2 text-center text-xl text-gray-600 flex justify-center mb-10" %>
            <%= f.text_field :name, class: "sign-name", placeholder: 'Name' %>
          </div>
        <div class="mb-3">
          <%= f.submit 'LOG IN', class: 'log-button' %>
        </div>
        <div class="flex text-sm justify-center">
          <p class="pr-1">Don't have an account?</p>
          <%= link_to 'Sign up', sign_up_path, class: "text-primaryLight font-bold" %>
        </div>
      </div> 
    <% end %>
  </div>